const JOBS = [
  {
    id: 'apt-guard',
    title: '아파트 경비원 (주간)',
    company: '그린힐 관리사무소',
    location: '서울 강북구',
    region: '서울',
    employmentType: '정규직',
    payType: '월급',
    price: '월 220만원',
    tags: [{ t: '정규직', cls: 'blue' }, { t: '마감임박 D-2', cls: 'warn' }, { t: '스폰서', cls: 'gold' }],
    views: 3420,
    liked: false,
    sponsor: true,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '서울 강북구 수유동', 근무시간: '주간 08:00~18:00 (교대)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '단지 내 주간 순찰 및 시설 관리 업무를 담당합니다. 입주민 응대와 택배·방문차량 관리를 포함하며, 처음 하시는 분도 선임 경비원이 1주일간 동행하며 알려드립니다.',
    duties: ['단지 내 주간 순찰 및 시설 점검', '입주민 · 방문객 응대, 택배 관리', '주차 관리 및 안전 점검'],
    quals: ['경력무관', '만 60세 이상 우대', '인근 거주자 우대', '경비 자격증 우대'],
    benefits: ['4대보험', '중식 제공', '명절 상여금', '근무복 지급'],
    companyInfo: { name: '그린힐 관리사무소', sub: '시설관리 · 직원 12명 · 2019년 설립' },
    contactVisible: true,
    contact: { name: '박영수', position: '관리소장', phone: '02-1234-5678' },
    inquiryEnabled: true
  },
  {
    id: 'school-meal',
    title: '학교 급식 조리원',
    company: '행복초등학교',
    location: '경기 성남시',
    region: '경기',
    employmentType: '파트타임',
    payType: '시급',
    price: '시급 12,000원',
    tags: [{ t: '파트타임', cls: 'blue' }, { t: '지원완료', cls: 'success' }],
    views: 2890,
    liked: true,
    sponsor: false,
    applied: true,
    crumb: '채용공고 > 조리·주방',
    info: { 근무지역: '경기 성남시 분당구', 근무시간: '평일 08:00~14:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '학교 급식실에서 조리 보조 및 배식, 뒷정리 업무를 담당합니다. 방학 기간 휴무로 근무 부담이 적고, 조리사 선생님과 함께 팀으로 일합니다.',
    duties: ['급식 재료 손질 및 조리 보조', '배식 및 식기 세척', '주방 위생 관리'],
    quals: ['경력무관', '조리 관련 자격 보유자 우대', '위생교육 이수 가능자'],
    benefits: ['4대보험', '방학 중 휴무', '중식 제공', '명절 상여금'],
    companyInfo: { name: '행복초등학교', sub: '교육기관 · 급식실 인원 6명' }
  },
  {
    id: 'parking',
    title: '주차관리 요원',
    company: '스마트파킹',
    location: '서울 송파구',
    region: '서울',
    employmentType: '정규직',
    payType: '월급',
    price: '월 205만원',
    tags: [{ t: '정규직', cls: 'blue' }, { t: '마감임박 D-2', cls: 'warn' }],
    views: 2150,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '서울 송파구 문정동', 근무시간: '2교대 (주/야간)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '상업시설 주차장에서 출입 차량 안내 및 정산, 시설 순찰 업무를 담당합니다. 실내 근무 위주이며 신입도 3일 현장 교육 후 바로 배치됩니다.',
    duties: ['출입 차량 안내 및 정산 지원', '주차장 내 순찰 및 안전 점검', '고객 응대'],
    quals: ['경력무관', '2교대 근무 가능자', '인근 거주자 우대'],
    benefits: ['4대보험', '교통비 지원', '명절 상여금', '근무복 지급'],
    companyInfo: { name: '스마트파킹', sub: '주차운영 · 직원 40명 · 2016년 설립' }
  },
  {
    id: 'library-desk',
    title: '지역 도서관 안내데스크',
    company: '시립도서관',
    location: '인천 남동구',
    region: '인천',
    employmentType: '계약직',
    payType: '월급',
    price: '월 195만원',
    tags: [{ t: '계약직', cls: 'blue' }],
    views: 1760,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 사무·안내',
    info: { 근무지역: '인천 남동구 구월동', 근무시간: '평일 09:00~18:00', 경력: '경력 무관', 학력: '고졸 이상' },
    desc: '도서관 안내데스크에서 대출·반납 처리와 방문객 안내를 담당합니다. 조용하고 규칙적인 근무 환경으로 컴퓨터 기본 사용이 가능하면 지원 가능합니다.',
    duties: ['도서 대출 · 반납 처리', '방문객 안내 및 좌석 관리', '도서 정리 및 서가 관리'],
    quals: ['경력무관', '기본 컴퓨터 사용 가능자', '친절한 응대 가능자'],
    benefits: ['4대보험', '주5일 근무', '도서관 시설 이용', '명절 상여금'],
    companyInfo: { name: '인천 남동구 시립도서관', sub: '공공기관 · 안내데스크 인원 8명' }
  },
  {
    id: 'delivery-sort',
    title: '택배 분류 상하차',
    company: 'CJ물류센터',
    location: '경기 이천시',
    region: '경기',
    employmentType: '일용직',
    payType: '일급',
    price: '일급 130,000원',
    tags: [{ t: '일용직', cls: 'blue' }],
    views: 980,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 물류·운송',
    info: { 근무지역: '경기 이천시 물류단지', 근무시간: '새벽 04:00~08:00 (일 단위)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '택배 물류센터에서 상품 분류 및 상하차 업무를 담당합니다. 하루 단위로 근무 신청이 가능해 원하는 날짜에만 일할 수 있습니다.',
    duties: ['택배 상품 분류 및 컨베이어 투입', '차량 상하차 지원', '작업장 정리'],
    quals: ['경력무관', '기본 체력 필요', '새벽 시간 근무 가능자'],
    benefits: ['일급 당일 지급', '작업복 · 장갑 지급', '무료 셔틀버스'],
    companyInfo: { name: 'CJ물류센터 이천', sub: '물류 · 상하차 인원 다수' }
  },
  {
    id: 'welfare-office',
    title: '노인복지관 사무보조',
    company: '행복복지관',
    location: '서울 노원구',
    region: '서울',
    employmentType: '계약직',
    payType: '월급',
    price: '월 180만원',
    tags: [{ t: '계약직', cls: 'blue' }, { t: '마감', cls: 'err' }],
    views: 1340,
    liked: false,
    sponsor: false,
    closed: true,
    crumb: '채용공고 > 사무·안내',
    info: { 근무지역: '서울 노원구 상계동', 근무시간: '평일 09:00~18:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '복지관 행정 업무 및 프로그램 접수, 어르신 안내 업무를 담당합니다. 사람을 상대하는 것을 좋아하는 분에게 잘 맞는 자리입니다.',
    duties: ['프로그램 접수 및 안내', '문서 정리 및 전화 응대', '행사 준비 보조'],
    quals: ['경력무관', '기본 문서작업 가능자', '원활한 소통 가능자'],
    benefits: ['4대보험', '주5일 근무', '중식 제공'],
    companyInfo: { name: '행복복지관', sub: '사회복지기관 · 직원 24명' }
  },
  {
    id: 'mart-cashier',
    title: '마트 계산원',
    company: '이마트 마포점',
    location: '서울 마포구',
    region: '서울',
    employmentType: '파트타임',
    payType: '시급',
    price: '시급 11,500원',
    tags: [{ t: '파트타임', cls: 'blue' }, { t: '스폰서', cls: 'gold' }],
    views: 1620,
    liked: false,
    sponsor: true,
    crumb: '채용공고 > 판매·서비스',
    info: { 근무지역: '서울 마포구 공덕동', 근무시간: '평일 09:00~14:00 (오전 타임)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '마트 계산대에서 결제 응대 및 상품 포장을 담당합니다. 오전 타임 고정 근무로 일정 관리가 편하고, 입사 후 3일간 계산기 사용법을 교육해드립니다.',
    duties: ['계산대 결제 응대', '상품 포장 및 정리', '매장 위생 점검'],
    quals: ['경력무관', '기본 계산 가능자', '친절한 응대 가능자'],
    benefits: ['4대보험', '직원 할인', '유니폼 지급', '명절 상여금'],
    companyInfo: { name: '이마트 마포점', sub: '유통 · 계산팀 인원 18명' }
  },
  {
    id: 'caregiver',
    title: '요양보호사',
    company: '행복요양원',
    location: '경기 수원시',
    region: '경기',
    employmentType: '정규직',
    payType: '월급',
    price: '월 235만원',
    tags: [{ t: '정규직', cls: 'blue' }, { t: '스폰서', cls: 'gold' }],
    views: 2410,
    liked: false,
    sponsor: true,
    crumb: '채용공고 > 요양·돌봄',
    info: { 근무지역: '경기 수원시 팔달구', 근무시간: '주간 08:00~17:00 (교대)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '요양원 내 어르신 일상생활 지원 및 케어 업무를 담당합니다. 요양보호사 자격증 보유자를 우대하며, 무자격자는 자격 취득 과정을 지원해드립니다.',
    duties: ['어르신 식사 · 이동 · 위생 보조', '건강 상태 관찰 및 기록', '프로그램 진행 보조'],
    quals: ['요양보호사 자격증 우대', '경력무관', '체력이 필요한 업무 가능자'],
    benefits: ['4대보험', '자격증 취득 지원', '중식 제공', '명절 상여금'],
    companyInfo: { name: '행복요양원', sub: '요양기관 · 직원 32명 · 2015년 설립' },
    inquiryEnabled: true
  },
  {
    id: 'cleaning',
    title: '아파트 미화원',
    company: '클린홈 관리',
    location: '인천 연수구',
    region: '인천',
    employmentType: '계약직',
    payType: '월급',
    price: '월 190만원',
    tags: [{ t: '계약직', cls: 'blue' }],
    views: 890,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '인천 연수구 송도동', 근무시간: '평일 07:00~13:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '아파트 단지 내 공용구역 청소 및 분리수거장 관리를 담당합니다. 오전 근무 위주로 오후 시간을 자유롭게 활용할 수 있습니다.',
    duties: ['공용구역 및 계단 청소', '분리수거장 관리', '단지 내 환경 정리'],
    quals: ['경력무관', '인근 거주자 우대'],
    benefits: ['4대보험', '청소용품 지급', '명절 상여금'],
    companyInfo: { name: '클린홈 관리', sub: '시설관리 · 직원 15명' }
  },
  {
    id: 'park-manager',
    title: '공원 관리원',
    company: '서울시설공단',
    location: '서울 강서구',
    region: '서울',
    employmentType: '정규직',
    payType: '월급',
    price: '월 200만원',
    tags: [{ t: '정규직', cls: 'blue' }, { t: '스폰서', cls: 'gold' }],
    views: 1980,
    liked: false,
    sponsor: true,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '서울 강서구 화곡동', 근무시간: '주간 09:00~18:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '공원 내 시설물 점검, 화단 관리, 이용객 안내 업무를 담당합니다. 실외 근무이며 계절별 조경 관리 교육을 지원합니다.',
    duties: ['공원 시설물 점검 및 관리', '화단 · 조경 관리', '이용객 안내 및 질서 유지'],
    quals: ['경력무관', '실외 근무 가능자', '기본 체력 필요'],
    benefits: ['4대보험', '작업복 지급', '명절 상여금'],
    companyInfo: { name: '서울시설공단', sub: '공공기관 · 공원관리팀 인원 20명' }
  },
  {
    id: 'warehouse-check',
    title: '물류센터 검수원',
    company: '쿠팡물류 용인센터',
    location: '경기 용인시',
    region: '경기',
    employmentType: '일용직',
    payType: '일급',
    price: '일급 125,000원',
    tags: [{ t: '일용직', cls: 'blue' }, { t: '스폰서', cls: 'gold' }],
    views: 1120,
    liked: false,
    sponsor: true,
    crumb: '채용공고 > 물류·운송',
    info: { 근무지역: '경기 용인시 물류센터', 근무시간: '오전 09:00~15:00 (일 단위)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '입고 상품의 수량 및 상태를 확인하는 검수 업무를 담당합니다. 앉아서 하는 작업 위주로 체력 부담이 적습니다.',
    duties: ['입고 상품 수량 · 상태 검수', '검수 결과 전산 입력', '불량품 분류'],
    quals: ['경력무관', '꼼꼼한 성격', '기본 스마트기기 사용 가능자'],
    benefits: ['일급 당일 지급', '냉난방 완비 작업장', '무료 셔틀버스'],
    companyInfo: { name: '쿠팡물류 용인센터', sub: '물류 · 검수팀 인원 다수' }
  },
  {
    id: 'cafe-hall',
    title: '카페 홀서빙',
    company: '커피언니 부평점',
    location: '인천 부평구',
    region: '인천',
    employmentType: '파트타임',
    payType: '시급',
    price: '시급 11,000원',
    tags: [{ t: '파트타임', cls: 'blue' }],
    views: 760,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 판매·서비스',
    info: { 근무지역: '인천 부평구 부평동', 근무시간: '평일 13:00~18:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '카페 홀에서 서빙 및 테이블 정리, 매장 응대 업무를 담당합니다. 오후 시간대 근무로 활동적으로 일하고 싶은 분께 추천합니다.',
    duties: ['테이블 서빙 및 정리', '매장 응대', '매장 청결 관리'],
    quals: ['경력무관', '활동적인 근무 가능자', '친절한 응대 가능자'],
    benefits: ['직원 음료 할인', '유니폼 지급', '주휴수당'],
    companyInfo: { name: '커피언니 부평점', sub: '외식 · 매장 인원 5명' }
  },
  {
    id: 'apt-guard-night',
    title: '아파트 경비원 (야간)',
    company: '그린힐 관리사무소',
    location: '서울 강북구',
    region: '서울',
    employmentType: '정규직',
    payType: '월급',
    price: '월 225만원',
    tags: [{ t: '정규직', cls: 'blue' }],
    views: 1480,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '서울 강북구 수유동', 근무시간: '야간 18:00~08:00 (교대)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '단지 내 야간 순찰 및 방범 업무를 담당합니다. 주간 근무자와 인수인계 체계가 잘 잡혀 있어 처음 하시는 분도 편하게 적응할 수 있습니다.',
    duties: ['단지 내 야간 순찰 및 방범', '출입 차량 · 방문객 통제', '비상 상황 초동 대응'],
    quals: ['경력무관', '만 60세 이상 우대', '야간 근무 가능자'],
    benefits: ['4대보험', '야간수당', '명절 상여금', '근무복 지급'],
    companyInfo: { name: '그린힐 관리사무소', sub: '시설관리 · 직원 12명 · 2019년 설립' },
    contactVisible: true,
    contact: { name: '박영수', position: '관리소장', phone: '02-1234-5678' },
    inquiryEnabled: true
  },
  {
    id: 'landscape-care',
    title: '단지 내 조경관리원',
    company: '그린힐 관리사무소',
    location: '서울 강북구',
    region: '서울',
    employmentType: '계약직',
    payType: '월급',
    price: '월 195만원',
    tags: [{ t: '계약직', cls: 'blue' }],
    views: 720,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '서울 강북구 수유동', 근무시간: '주간 08:00~17:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '단지 내 화단 및 조경수 관리, 계절별 식재 작업을 담당합니다. 실외 근무로 몸을 움직이는 것을 좋아하는 분께 추천합니다.',
    duties: ['화단 · 조경수 관리', '계절별 식재 및 전정 작업', '단지 내 환경 정리'],
    quals: ['경력무관', '실외 근무 가능자', '기본 체력 필요'],
    benefits: ['4대보험', '작업복 · 장비 지급', '명절 상여금'],
    companyInfo: { name: '그린힐 관리사무소', sub: '시설관리 · 직원 12명 · 2019년 설립' },
    contactVisible: true,
    contact: { name: '박영수', position: '관리소장', phone: '02-1234-5678' }
  },
  {
    id: 'life-counselor',
    title: '생활지도사',
    company: '행복요양원',
    location: '경기 수원시',
    region: '경기',
    employmentType: '정규직',
    payType: '월급',
    price: '월 220만원',
    tags: [{ t: '정규직', cls: 'blue' }],
    views: 1150,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 요양·돌봄',
    info: { 근무지역: '경기 수원시 팔달구', 근무시간: '주간 08:00~17:00 (교대)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '어르신들의 여가 프로그램 진행 및 일상생활 상담을 담당합니다. 사람들과 소통하는 것을 좋아하는 분에게 잘 맞는 자리입니다.',
    duties: ['여가 프로그램 기획 및 진행', '어르신 상담 및 생활 지도', '가족 문의 응대'],
    quals: ['경력무관', '원활한 소통 가능자', '프로그램 진행 경험 우대'],
    benefits: ['4대보험', '자격증 취득 지원', '중식 제공', '명절 상여금'],
    companyInfo: { name: '행복요양원', sub: '요양기관 · 직원 32명 · 2015년 설립' }
  },
  {
    id: 'care-kitchen',
    title: '요양원 조리보조',
    company: '행복요양원',
    location: '경기 수원시',
    region: '경기',
    employmentType: '파트타임',
    payType: '시급',
    price: '시급 11,800원',
    tags: [{ t: '파트타임', cls: 'blue' }],
    views: 640,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 조리·주방',
    info: { 근무지역: '경기 수원시 팔달구', 근무시간: '평일 07:00~13:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '요양원 급식실에서 어르신 식사 조리 보조 및 배식을 담당합니다. 오전 시간대 근무로 오후 시간을 자유롭게 쓸 수 있습니다.',
    duties: ['식사 조리 보조 및 배식', '주방 위생 관리', '식자재 손질'],
    quals: ['경력무관', '위생교육 이수 가능자'],
    benefits: ['4대보험', '중식 제공', '명절 상여금'],
    companyInfo: { name: '행복요양원', sub: '요양기관 · 직원 32명 · 2015년 설립' }
  },
  {
    id: 'mart-shelf',
    title: '매장 진열 관리원',
    company: '이마트 마포점',
    location: '서울 마포구',
    region: '서울',
    employmentType: '파트타임',
    payType: '시급',
    price: '시급 11,500원',
    tags: [{ t: '파트타임', cls: 'blue' }],
    views: 880,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 판매·서비스',
    info: { 근무지역: '서울 마포구 공덕동', 근무시간: '평일 14:00~19:00 (오후 타임)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '매대 상품 진열 및 재고 정리, 유통기한 점검 업무를 담당합니다. 오후 타임 고정 근무로 일정 관리가 편합니다.',
    duties: ['매대 상품 진열 및 보충', '유통기한 점검', '재고 정리'],
    quals: ['경력무관', '기본 체력 필요'],
    benefits: ['4대보험', '직원 할인', '유니폼 지급'],
    companyInfo: { name: '이마트 마포점', sub: '유통 · 계산팀 인원 18명' }
  },
  {
    id: 'mart-info',
    title: '고객응대 도우미',
    company: '이마트 마포점',
    location: '서울 마포구',
    region: '서울',
    employmentType: '계약직',
    payType: '월급',
    price: '월 192만원',
    tags: [{ t: '계약직', cls: 'blue' }],
    views: 590,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 판매·서비스',
    info: { 근무지역: '서울 마포구 공덕동', 근무시간: '평일 10:00~19:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '매장 안내데스크에서 고객 문의 응대 및 반품 · 교환 접수를 담당합니다. 친절한 응대를 좋아하는 분에게 추천합니다.',
    duties: ['고객 문의 응대', '반품 · 교환 접수', '안내데스크 운영'],
    quals: ['경력무관', '친절한 응대 가능자', '기본 컴퓨터 사용 가능자'],
    benefits: ['4대보험', '직원 할인', '명절 상여금'],
    companyInfo: { name: '이마트 마포점', sub: '유통 · 계산팀 인원 18명' }
  },
  {
    id: 'sports-guide',
    title: '체육시설 안내원',
    company: '서울시설공단',
    location: '서울 강서구',
    region: '서울',
    employmentType: '계약직',
    payType: '월급',
    price: '월 190만원',
    tags: [{ t: '계약직', cls: 'blue' }],
    views: 810,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 사무·안내',
    info: { 근무지역: '서울 강서구 화곡동', 근무시간: '평일 09:00~18:00 (교대)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '공공 체육시설 이용 안내 및 시설 예약 접수를 담당합니다. 규칙적인 근무 환경에서 일하고 싶은 분께 추천합니다.',
    duties: ['시설 이용 안내 및 예약 접수', '이용객 질서 유지', '시설 점검 지원'],
    quals: ['경력무관', '기본 컴퓨터 사용 가능자', '친절한 응대 가능자'],
    benefits: ['4대보험', '주5일 근무', '명절 상여금'],
    companyInfo: { name: '서울시설공단', sub: '공공기관 · 공원관리팀 인원 20명' }
  },
  {
    id: 'parking-facility',
    title: '주차시설 관리원',
    company: '서울시설공단',
    location: '서울 강서구',
    region: '서울',
    employmentType: '정규직',
    payType: '월급',
    price: '월 205만원',
    tags: [{ t: '정규직', cls: 'blue' }],
    views: 930,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 시설·경비',
    info: { 근무지역: '서울 강서구 화곡동', 근무시간: '2교대 (주/야간)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '공영주차장 시설 점검 및 정산 업무를 담당합니다. 안정적인 공공기관 근무 환경에서 장기 근속이 가능합니다.',
    duties: ['주차시설 점검 및 정산', '이용객 안내', '안전 점검'],
    quals: ['경력무관', '2교대 근무 가능자'],
    benefits: ['4대보험', '교통비 지원', '명절 상여금', '근무복 지급'],
    companyInfo: { name: '서울시설공단', sub: '공공기관 · 공원관리팀 인원 20명' }
  },
  {
    id: 'delivery-pack',
    title: '택배 포장원',
    company: '쿠팡물류 용인센터',
    location: '경기 용인시',
    region: '경기',
    employmentType: '일용직',
    payType: '일급',
    price: '일급 122,000원',
    tags: [{ t: '일용직', cls: 'blue' }],
    views: 700,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 물류·운송',
    info: { 근무지역: '경기 용인시 물류센터', 근무시간: '오전 08:00~14:00 (일 단위)', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '출고 상품의 포장 및 라벨 부착 업무를 담당합니다. 앉아서 하는 작업 위주로 체력 부담이 적습니다.',
    duties: ['출고 상품 포장', '라벨 부착 및 검수', '포장재 정리'],
    quals: ['경력무관', '꼼꼼한 성격'],
    benefits: ['일급 당일 지급', '냉난방 완비 작업장', '무료 셔틀버스'],
    companyInfo: { name: '쿠팡물류 용인센터', sub: '물류 · 검수팀 인원 다수' }
  },
  {
    id: 'inout-manage',
    title: '입출고 관리보조',
    company: '쿠팡물류 용인센터',
    location: '경기 용인시',
    region: '경기',
    employmentType: '계약직',
    payType: '월급',
    price: '월 210만원',
    tags: [{ t: '계약직', cls: 'blue' }],
    views: 560,
    liked: false,
    sponsor: false,
    crumb: '채용공고 > 물류·운송',
    info: { 근무지역: '경기 용인시 물류센터', 근무시간: '평일 09:00~18:00', 경력: '경력 무관', 학력: '학력 무관' },
    desc: '입출고 현황을 전산으로 기록하고 재고 수량을 관리하는 업무를 담당합니다. 기본적인 컴퓨터 사용이 가능하면 지원 가능합니다.',
    duties: ['입출고 현황 전산 기록', '재고 수량 관리', '현장 담당자와 소통'],
    quals: ['경력무관', '기본 컴퓨터 사용 가능자', '꼼꼼한 성격'],
    benefits: ['4대보험', '냉난방 완비 작업장', '무료 셔틀버스', '명절 상여금'],
    companyInfo: { name: '쿠팡물류 용인센터', sub: '물류 · 검수팀 인원 다수' }
  }
];

function jobById(id){ return JOBS.find(j => j.id === id); }
